image: docker:20.10.16

services:
  - docker:20.10.16-dind

variables:
  CI_DEBUG_SERVICES: "true"

  # When using dind service, you must instruct Docker to talk with
  # the daemon started inside of the service. The daemon is available
  # with a network connection instead of the default
  # /var/run/docker.sock socket.
  DOCKER_HOST: tcp://docker:2376

  # The 'docker' hostname is the alias of the service container as described at
  # https://docs.gitlab.com/ee/ci/services/#accessing-the-services.
  # If you're using GitLab Runner 12.7 or earlier with the Kubernetes executor and Kubernetes 1.6 or earlier,
  # the variable must be set to tcp://localhost:2376 because of how the
  # Kubernetes executor connects services to the job container
  # DOCKER_HOST: tcp://localhost:2376
  #
  # Specify to Docker where to create the certificates. Docker
  # creates them automatically on boot, and creates
  # `/certs/client` to share between the service and job
  # container, thanks to volume mount from config.toml

  DOCKER_TLS_CERTDIR: "/certs"

  # These are usually specified by the entrypoint, however the
  # Kubernetes executor doesn't run entrypoints
  # https://gitlab.com/gitlab-org/gitlab-runner/-/issues/4125

  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  DOCKER_DRIVER: overlay2

  CONTAINER_TAG: ${CI_PIPELINE_IID}

stages:
  - build
  - deploy

before_script:
  - docker info
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY" 

build-backend:
  stage: build
  image: docker:24.0
  services:
    - name: docker:24.0-dind
  script:
    - echo Building container "$CI_REGISTRY_IMAGE/backend-app:$CONTAINER_TAG"
    - docker build -t "$CI_REGISTRY_IMAGE/backend-app:latest" platform/backend
    - docker build -t "$CI_REGISTRY_IMAGE/backend-app:$CONTAINER_TAG" platform/backend
    - docker push "$CI_REGISTRY_IMAGE/backend-app:latest"
    - docker push "$CI_REGISTRY_IMAGE/backend-app:$CONTAINER_TAG"
  # rules:
  #   - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  #     changes:
  #       - platform/backend/**/*
  #     when: always
  #   - if: $CI_PIPELINE_SOURCE == "push"
  #     changes:
  #       - platform/backend/**/*
  #     when: always

build-frontend:
  stage: build
  image: docker:24.0
  services:
    - name: docker:24.0-dind
  script:
    - echo Building container "$CI_REGISTRY_IMAGE/backend-app:$CONTAINER_TAG"
    - docker build -t "$CI_REGISTRY_IMAGE/frontend-app:latest" platform/frontend
    - docker build -t "$CI_REGISTRY_IMAGE/frontend-app:$CONTAINER_TAG" platform/frontend
    - docker push "$CI_REGISTRY_IMAGE/frontend-app:latest"
    - docker push "$CI_REGISTRY_IMAGE/frontend-app:$CONTAINER_TAG"
  # rules:
  #   - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  #     changes:
  #       - platform/frontend/**/*
  #     when: always
  #   - if: $CI_PIPELINE_SOURCE == "push"
  #     changes:
  #       - platform/frontend/**/*
  #     when: always

