replicaCount: 2

image:
  repository: registry.gitlab.com/full-stack-template/full-stack-template/backend-app
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets:
  - name: full-stack-template-registry-credentials

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000
  runAsNonRoot: true

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

env:
  NODE_ENV: production

networkPolicy:
  enabled: true
  egress:
    - to:
        - ipBlock:
            cidr: 192.168.111.95/32
      ports:
        - port: 5432
          protocol: TCP
    # Allow DNS lookups
    - to:
        - namespaceSelector: {}
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP

database:
  host: "postgresql"
  port: "5432"
  name: "stocksgraph"
  credentials:
    username: "postgres"
    password: "changeme"