apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-db-credentials
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.database.credentials.username | b64enc }}
  password: {{ .Values.database.credentials.password | b64enc }} 