apiVersion: v2
name: full-stack-template
description: A Helm chart for the full-stack-template application
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: backend
    version: 0.1.0
    repository: file://charts/backend
  - name: frontend
    version: 0.1.0
    repository: file://charts/frontend 