replicaCount: 2

image:
  repository: registry.gitlab.com/full-stack-template/full-stack-template/frontend-app
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets:
  - name: full-stack-template-registry-credentials

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 101
  runAsUser: 101
  runAsNonRoot: true

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 101

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

env:
  NODE_ENV: production

networkPolicy:
  enabled: true
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: backend
              app.kubernetes.io/instance: full-stack-template 